theme: jekyll-theme-midnight
#remote_theme: mmistakes/so-simple-theme
#remote_theme: chrisbobbe/jekyll-theme-prologue
#remote_theme: samarsault/texture
#remote_theme: fongandrew/hydeout
title: Welcome to my burough, a den of an ecletic assortment of stuff
